/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 50252f4da01f91321fa3813a6c5f0918)
interface __BaseEnv_Env {
	DB: D1Database;
	METRICS: AnalyticsEngineDataset;
	SUMMARIES: Queue;
	AI: Ai;
	AI_PAID_GATEWAY: string;
	AI_MONTHLY_CAP_INR: string;
	AI_PERSON_CAP_INR: string;
	USD_INR: string;
	ENVIRONMENT: string;
	BASE_URL: string;
	BETTER_AUTH_SECRET: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	ADMIN_EMAILS: string;
	ANALYTICS_TOKEN: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	TELEGRAM_BOT_TOKEN: string;
	APPLE_TEAM_ID: string;
	AI_FAKE: string;
	BOOKINGS: DurableObjectNamespace<import("./src/index").BookingObject>;
	PEOPLE: DurableObjectNamespace<import("./src/index").PersonObject>;
	MONTHS: DurableObjectNamespace<import("./src/index").MonthIndexObject>;
	PENDING: DurableObjectNamespace<import("./src/index").PendingObject>;
	INBOX: DurableObjectNamespace<import("./src/index").InboxObject>;
	LIBRARIES: DurableObjectNamespace<import("./src/index").LibraryObject>;
	SPACES: DurableObjectNamespace<import("./src/index").SpaceObject>;
	CHATS: DurableObjectNamespace<import("./src/index").ChatObject>;
	BUDGET: DurableObjectNamespace<import("./src/index").BudgetObject>;
	LIVE: DurableObjectNamespace<import("./src/index").LiveObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "BookingObject" | "PersonObject" | "MonthIndexObject" | "PendingObject" | "InboxObject" | "LibraryObject" | "SpaceObject" | "ChatObject" | "BudgetObject" | "LiveObject";
	}
	interface ProductionEnv {
		DB: D1Database;
		METRICS: AnalyticsEngineDataset;
		SUMMARIES: Queue;
		AI: Ai;
		AI_PAID_GATEWAY: string;
		AI_MONTHLY_CAP_INR: string;
		AI_PERSON_CAP_INR: string;
		USD_INR: string;
		ENVIRONMENT: string;
		BASE_URL: string;
		BETTER_AUTH_SECRET: string;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		ADMIN_EMAILS: string;
		ANALYTICS_TOKEN: string;
		CLOUDFLARE_ACCOUNT_ID: string;
		TELEGRAM_BOT_TOKEN: string;
		APPLE_TEAM_ID: string;
		AI_FAKE: string;
		BOOKINGS: DurableObjectNamespace<import("./src/index").BookingObject>;
		PEOPLE: DurableObjectNamespace<import("./src/index").PersonObject>;
		MONTHS: DurableObjectNamespace<import("./src/index").MonthIndexObject>;
		PENDING: DurableObjectNamespace<import("./src/index").PendingObject>;
		INBOX: DurableObjectNamespace<import("./src/index").InboxObject>;
		LIBRARIES: DurableObjectNamespace<import("./src/index").LibraryObject>;
		SPACES: DurableObjectNamespace<import("./src/index").SpaceObject>;
		CHATS: DurableObjectNamespace<import("./src/index").ChatObject>;
		BUDGET: DurableObjectNamespace<import("./src/index").BudgetObject>;
		LIVE: DurableObjectNamespace<import("./src/index").LiveObject>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AI_PAID_GATEWAY" | "AI_MONTHLY_CAP_INR" | "AI_PERSON_CAP_INR" | "USD_INR" | "ENVIRONMENT" | "BASE_URL" | "BETTER_AUTH_SECRET" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "ADMIN_EMAILS" | "ANALYTICS_TOKEN" | "CLOUDFLARE_ACCOUNT_ID" | "TELEGRAM_BOT_TOKEN" | "APPLE_TEAM_ID" | "AI_FAKE">> {}
}
