// Gig-centric gig operations (docs/design/gig-centric.md, step 2). Routes live under
// /api/gigs (user-scoped: access is decided by each gig's own people and roles, not by a
// workspace). Writes keep their idempotency and audit inside the gig's object.
import {
  AddEventInput,
  AddPersonInput,
  BookingRef,
  BookingStatusInput,
  CreateBookingInput,
  EventRef,
  FindMyGigsInput,
  PersonRef,
  UpdateBookingInput,
  UpdateEventInput,
  UpdatePersonInput,
} from "@assistant/shared";
import { defineOperation } from "../../core/operations.ts";
import * as b from "./services/bookings.ts";

export const bookingOperations = [
  defineOperation({
    id: "gigs.create_booking",
    tool: "create_gig",
    description:
      "Create a gig with one or more events (date, time, venue) and the people on it. You become its manager. Times without an offset are India time.",
    scope: "user",
    kind: "write",
    idempotency: "object",
    http: { method: "POST", path: "/gigs", status: 201 },
    input: CreateBookingInput,
    handler: (ctx, input) => b.createBooking(ctx, input),
  }),
  defineOperation({
    id: "gigs.find_my_gigs",
    tool: "find_my_gigs",
    description:
      "My gigs' events, soonest first (or latest first with order=desc), optionally between two times. May lag a few seconds behind changes.",
    scope: "user",
    kind: "read",
    http: { method: "GET", path: "/me/gigs" },
    input: FindMyGigsInput,
    handler: (ctx, input) => b.findMyGigs(ctx, input),
  }),
  defineOperation({
    id: "gigs.get_booking",
    tool: "get_gig",
    description: "A gig's details, events and people (only for people on the gig).",
    scope: "user",
    kind: "read",
    http: { method: "GET", path: "/gigs/:gig_id" },
    input: BookingRef,
    handler: (ctx, input) => b.getBooking(ctx, input.gig_id),
  }),
  defineOperation({
    id: "gigs.update_booking",
    tool: "update_gig",
    description:
      "Change a gig's title, type, client or notes (managers). Send the version you last saw; if someone changed the gig since, you get a conflict and should reload.",
    scope: "user",
    kind: "write",
    idempotency: "object",
    http: { method: "PATCH", path: "/gigs/:gig_id" },
    input: UpdateBookingInput,
    handler: (ctx, input) => b.updateBooking(ctx, input),
  }),
  defineOperation({
    id: "gigs.set_booking_status",
    tool: "set_gig_status",
    description:
      "Confirm, complete or cancel a gig (managers). enquiry → confirmed → completed; enquiry or confirmed → cancelled.",
    scope: "user",
    kind: "write",
    idempotency: "object",
    confirm: true,
    http: { method: "POST", path: "/gigs/:gig_id/status" },
    input: BookingStatusInput,
    handler: (ctx, input) => b.setBookingStatus(ctx, input),
  }),
  defineOperation({
    id: "gigs.delete_booking",
    tool: "delete_gig",
    description: "Delete a gig entered by mistake (managers). To call off a real gig, cancel it instead.",
    scope: "user",
    kind: "write",
    idempotency: "object",
    confirm: true,
    http: { method: "DELETE", path: "/gigs/:gig_id" },
    input: BookingRef,
    handler: (ctx, input) => b.deleteBooking(ctx, input.gig_id),
  }),
  defineOperation({
    id: "gigs.get_booking_history",
    tool: "get_gig_history",
    description: "Who changed what on a gig, newest first (managers).",
    scope: "user",
    kind: "read",
    http: { method: "GET", path: "/gigs/:gig_id/history" },
    input: BookingRef,
    handler: (ctx, input) => b.bookingHistory(ctx, input.gig_id),
  }),
  defineOperation({
    id: "gigs.add_booking_event",
    tool: "add_gig_event",
    description: 'Add an event to a gig, e.g. a "Reception" after the "Sangeet" (managers).',
    scope: "user",
    kind: "write",
    idempotency: "object",
    http: { method: "POST", path: "/gigs/:gig_id/events", status: 201 },
    input: AddEventInput,
    handler: (ctx, input) => b.addBookingEvent(ctx, input),
  }),
  defineOperation({
    id: "gigs.update_booking_event",
    tool: "update_gig_event",
    description: "Change an event's title, time, venue or notes (managers; send the gig's version).",
    scope: "user",
    kind: "write",
    idempotency: "object",
    http: { method: "PATCH", path: "/gigs/:gig_id/events/:event_id" },
    input: UpdateEventInput,
    handler: (ctx, input) => b.updateBookingEvent(ctx, input),
  }),
  defineOperation({
    id: "gigs.remove_booking_event",
    tool: "remove_gig_event",
    description: "Remove an event from a gig (managers). A gig keeps at least one event.",
    scope: "user",
    kind: "write",
    idempotency: "object",
    confirm: true,
    http: { method: "DELETE", path: "/gigs/:gig_id/events/:event_id" },
    input: EventRef,
    handler: (ctx, input) => b.removeBookingEvent(ctx, input.gig_id, input.event_id),
  }),
  defineOperation({
    id: "gigs.add_booking_person",
    tool: "add_gig_person",
    description:
      "Add someone to a gig as a manager or player (managers). Give their user_id, their email (matched to an account if they have one) or just a name.",
    scope: "user",
    kind: "write",
    idempotency: "object",
    http: { method: "POST", path: "/gigs/:gig_id/people", status: 201 },
    input: AddPersonInput,
    handler: (ctx, input) => b.addBookingPerson(ctx, input),
  }),
  defineOperation({
    id: "gigs.update_booking_person",
    tool: "update_gig_person",
    description: "Change someone's role or name on a gig (managers). A gig keeps at least one manager.",
    scope: "user",
    kind: "write",
    idempotency: "object",
    http: { method: "PATCH", path: "/gigs/:gig_id/people/:person_id" },
    input: UpdatePersonInput,
    handler: (ctx, input) => b.updateBookingPerson(ctx, input),
  }),
  defineOperation({
    id: "gigs.remove_booking_person",
    tool: "remove_gig_person",
    description: "Remove someone from a gig (managers). A gig keeps at least one manager.",
    scope: "user",
    kind: "write",
    idempotency: "object",
    confirm: true,
    http: { method: "DELETE", path: "/gigs/:gig_id/people/:person_id" },
    input: PersonRef,
    handler: (ctx, input) => b.removeBookingPerson(ctx, input.gig_id, input.person_id),
  }),
];
