// Gigs module operations (docs/api.md). Each is an HTTP route under
// /api/w/:workspaceId and, from T10, an MCP tool with the same name.
import {
  CancelGigInput,
  CreateMusicianInput,
  ExpenseRef,
  FindExpensesInput,
  FindMusiciansInput,
  MusicianRef,
  PaymentRef,
  PayoutRef,
  RecordExpenseInput,
  RecordPaymentInput,
  RecordPayoutInput,
  SetLineupInput,
  UpdateMusicianInput,
  ClientRef,
  CreateClientInput,
  CreateGigInput,
  CreateVenueInput,
  FindClientsInput,
  FindGigsInput,
  FindVenuesInput,
  GigRef,
  UpdateClientInput,
  UpdateGigInput,
  UpdateGigsSettingsInput,
  UpdateVenueInput,
  VenueRef,
} from "@assistant/shared";
import { z } from "zod";
import { defineOperation } from "../../core/operations.ts";
import * as c from "./services/clients.ts";
import * as v from "./services/venues.ts";
import * as g from "./services/gigs.ts";
import * as pay from "./services/payments.ts";
import * as band from "./services/band.ts";
import * as me from "./services/me.ts";
import * as settings from "./services/settings.ts";

export const gigsOperations = [
  // --- Clients ---
  defineOperation({
    id: "gigs.create_client",
    tool: "create_client",
    description: "Add a client (the person or company booking gigs).",
    scope: "workspace",
    kind: "write",
    http: { method: "POST", path: "/clients", status: 201 },
    input: CreateClientInput,
    handler: (ctx, input) => c.createClient(ctx, input),
  }),
  defineOperation({
    id: "gigs.find_clients",
    tool: "find_clients",
    description: "List clients, optionally searching by name, phone or organisation.",
    scope: "workspace",
    kind: "read",
    http: { method: "GET", path: "/clients" },
    input: FindClientsInput,
    handler: (ctx, input) => c.findClients(ctx, input),
  }),
  defineOperation({
    id: "gigs.get_client_history",
    tool: "get_client_history",
    description: "A client's details and all their gigs, newest first.",
    scope: "workspace",
    kind: "read",
    http: { method: "GET", path: "/clients/:client_id" },
    input: ClientRef,
    handler: (ctx, input) => c.clientHistory(ctx, input.client_id),
  }),
  defineOperation({
    id: "gigs.update_client",
    tool: "update_client",
    description: "Change a client's details. Omitted fields stay the same; null clears a field.",
    scope: "workspace",
    kind: "write",
    http: { method: "PATCH", path: "/clients/:client_id" },
    input: UpdateClientInput,
    handler: (ctx, input) => c.updateClient(ctx, input),
  }),
  defineOperation({
    id: "gigs.delete_client",
    tool: "delete_client",
    description: "Delete a client. Their gigs keep a reference to them.",
    scope: "workspace",
    kind: "write",
    confirm: true,
    http: { method: "DELETE", path: "/clients/:client_id" },
    input: ClientRef,
    handler: (ctx, input) => c.deleteClient(ctx, input.client_id),
  }),

  // --- Venues ---
  defineOperation({
    id: "gigs.create_venue",
    tool: "create_venue",
    description: "Add a venue.",
    scope: "workspace",
    kind: "write",
    http: { method: "POST", path: "/venues", status: 201 },
    input: CreateVenueInput,
    handler: (ctx, input) => v.createVenue(ctx, input),
  }),
  defineOperation({
    id: "gigs.find_venues",
    tool: "find_venues",
    description: "List venues, optionally searching by name or city.",
    scope: "workspace",
    kind: "read",
    http: { method: "GET", path: "/venues" },
    input: FindVenuesInput,
    handler: (ctx, input) => v.findVenues(ctx, input),
  }),
  defineOperation({
    id: "gigs.update_venue",
    tool: "update_venue",
    description: "Change a venue's details. Omitted fields stay the same; null clears a field.",
    scope: "workspace",
    kind: "write",
    http: { method: "PATCH", path: "/venues/:venue_id" },
    input: UpdateVenueInput,
    handler: (ctx, input) => v.updateVenue(ctx, input),
  }),
  defineOperation({
    id: "gigs.delete_venue",
    tool: "delete_venue",
    description: "Delete a venue. Gigs there keep a reference to it.",
    scope: "workspace",
    kind: "write",
    confirm: true,
    http: { method: "DELETE", path: "/venues/:venue_id" },
    input: VenueRef,
    handler: (ctx, input) => v.deleteVenue(ctx, input.venue_id),
  }),

  // --- Gigs ---
  defineOperation({
    id: "gigs.create_gig",
    tool: "create_gig",
    description:
      "Add a gig. Times are India time unless an offset is given. Client and venue can be given by id or exact name; ambiguous names return candidates.",
    scope: "workspace",
    kind: "write",
    http: { method: "POST", path: "/gigs", status: 201 },
    input: CreateGigInput,
    handler: (ctx, input) => g.createGig(ctx, input),
  }),
  defineOperation({
    id: "gigs.find_gigs",
    tool: "find_gigs",
    description: "List gigs by start time, filtered by date range, status, client, venue or title.",
    scope: "workspace",
    kind: "read",
    http: { method: "GET", path: "/gigs" },
    input: FindGigsInput,
    handler: (ctx, input) => g.findGigs(ctx, input),
  }),
  defineOperation({
    id: "gigs.get_gig",
    tool: "get_gig",
    description: "One gig with its client, venue and fee.",
    scope: "workspace",
    kind: "read",
    http: { method: "GET", path: "/gigs/:gig_id" },
    input: GigRef,
    handler: (ctx, input) => g.getGig(ctx, input.gig_id),
  }),
  defineOperation({
    id: "gigs.update_gig",
    tool: "update_gig",
    description:
      "Change a gig's details (not its status). Omitted fields stay the same; null clears a field.",
    scope: "workspace",
    kind: "write",
    http: { method: "PATCH", path: "/gigs/:gig_id" },
    input: UpdateGigInput,
    handler: (ctx, input) => g.updateGig(ctx, input),
  }),
  defineOperation({
    id: "gigs.confirm_gig",
    tool: "confirm_gig",
    description: "Mark an enquiry as confirmed.",
    scope: "workspace",
    kind: "write",
    http: { method: "POST", path: "/gigs/:gig_id/confirm" },
    input: GigRef,
    handler: (ctx, input) => g.setGigStatus(ctx, input.gig_id, "confirmed"),
  }),
  defineOperation({
    id: "gigs.complete_gig",
    tool: "complete_gig",
    description: "Mark a gig as played.",
    scope: "workspace",
    kind: "write",
    http: { method: "POST", path: "/gigs/:gig_id/complete" },
    input: GigRef,
    handler: (ctx, input) => g.setGigStatus(ctx, input.gig_id, "completed"),
  }),
  defineOperation({
    id: "gigs.cancel_gig",
    tool: "cancel_gig",
    description: "Cancel a gig that hasn't been played, with an optional reason.",
    scope: "workspace",
    kind: "write",
    confirm: true,
    http: { method: "POST", path: "/gigs/:gig_id/cancel" },
    input: CancelGigInput,
    handler: (ctx, input) => g.cancelGig(ctx, input),
  }),
  defineOperation({
    id: "gigs.delete_gig",
    tool: "delete_gig",
    description: "Delete a gig entered by mistake (only if no payments are recorded; otherwise cancel it).",
    scope: "workspace",
    kind: "write",
    confirm: true,
    http: { method: "DELETE", path: "/gigs/:gig_id" },
    input: GigRef,
    handler: (ctx, input) => g.deleteGig(ctx, input.gig_id),
  }),

  // --- Money: client payments and expenses ---
  defineOperation({
    id: "gigs.get_gig_money",
    tool: "get_gig_money",
    description:
      "A gig's money: fee, payments received, balance and status, lineup shares and payouts; for owners also expenses and net. Members only see their own share.",
    scope: "workspace",
    kind: "read",
    http: { method: "GET", path: "/gigs/:gig_id/money" },
    input: GigRef,
    handler: (ctx, input) => band.getGigMoney(ctx, input.gig_id),
  }),
  defineOperation({
    id: "gigs.record_payment",
    tool: "record_payment",
    description: "Record money received from the client for a gig (full or partial). Date defaults to today.",
    scope: "workspace",
    kind: "write",
    confirm: true,
    http: { method: "POST", path: "/gigs/:gig_id/payments", status: 201 },
    input: RecordPaymentInput,
    handler: (ctx, input) => pay.recordPayment(ctx, input),
  }),
  defineOperation({
    id: "gigs.reverse_payment",
    tool: "reverse_payment",
    description:
      "Correct a payment recorded by mistake by adding a reversing entry (payments are never edited).",
    scope: "workspace",
    kind: "write",
    confirm: true,
    http: { method: "POST", path: "/payments/:payment_id/reverse", status: 201 },
    input: PaymentRef,
    handler: (ctx, input) => pay.reversePayment(ctx, input.payment_id, input.note),
  }),
  defineOperation({
    id: "gigs.record_expense",
    tool: "record_expense",
    description:
      "Record an expense (travel, food, equipment…), optionally for a gig. Date defaults to today.",
    scope: "workspace",
    kind: "write",
    confirm: true,
    http: { method: "POST", path: "/expenses", status: 201 },
    input: RecordExpenseInput,
    handler: (ctx, input) => pay.recordExpense(ctx, input),
  }),
  defineOperation({
    id: "gigs.find_expenses",
    tool: "find_expenses",
    description: "List expenses, newest first, by date range or gig.",
    scope: "workspace",
    kind: "read",
    role: "owner",
    http: { method: "GET", path: "/expenses" },
    input: FindExpensesInput,
    handler: (ctx, input) => pay.findExpenses(ctx, input),
  }),
  defineOperation({
    id: "gigs.delete_expense",
    tool: "delete_expense",
    description: "Delete an expense recorded by mistake.",
    scope: "workspace",
    kind: "write",
    confirm: true,
    http: { method: "DELETE", path: "/expenses/:expense_id" },
    input: ExpenseRef,
    handler: (ctx, input) => pay.deleteExpense(ctx, input.expense_id),
  }),

  // --- Band roster, lineups and payouts ---
  defineOperation({
    id: "gigs.create_musician",
    tool: "create_musician",
    description: "Add a musician to the collective's roster (members, deps, session players).",
    scope: "workspace",
    kind: "write",
    http: { method: "POST", path: "/musicians", status: 201 },
    input: CreateMusicianInput,
    handler: (ctx, input) => band.createMusician(ctx, input),
  }),
  defineOperation({
    id: "gigs.find_musicians",
    tool: "find_musicians",
    description: "List the collective's roster.",
    scope: "workspace",
    kind: "read",
    http: { method: "GET", path: "/musicians" },
    input: FindMusiciansInput,
    handler: (ctx, input) => band.findMusicians(ctx, input),
  }),
  defineOperation({
    id: "gigs.update_musician",
    tool: "update_musician",
    description: "Change a roster entry. Omitted fields stay the same; null clears a field.",
    scope: "workspace",
    kind: "write",
    role: "owner",
    http: { method: "PATCH", path: "/musicians/:musician_id" },
    input: UpdateMusicianInput,
    handler: (ctx, input) => band.updateMusician(ctx, input),
  }),
  defineOperation({
    id: "gigs.delete_musician",
    tool: "delete_musician",
    description: "Remove someone from the roster (past lineups and payouts are kept).",
    scope: "workspace",
    kind: "write",
    role: "owner",
    confirm: true,
    http: { method: "DELETE", path: "/musicians/:musician_id" },
    input: MusicianRef,
    handler: (ctx, input) => band.deleteMusician(ctx, input.musician_id),
  }),
  defineOperation({
    id: "gigs.set_gig_lineup",
    tool: "set_gig_lineup",
    description:
      'Set who plays a gig and each person\'s share (amount, percent, or split: "equal" of the fee or split_total). Replaces the current lineup.',
    scope: "workspace",
    kind: "write",
    confirm: true,
    http: { method: "PUT", path: "/gigs/:gig_id/lineup" },
    input: SetLineupInput,
    handler: (ctx, input) => band.setLineup(ctx, input),
  }),
  defineOperation({
    id: "gigs.record_payout",
    tool: "record_payout",
    description: "Record money the collective paid a musician for a gig. Date defaults to today.",
    scope: "workspace",
    kind: "write",
    confirm: true,
    http: { method: "POST", path: "/gigs/:gig_id/payouts", status: 201 },
    input: RecordPayoutInput,
    handler: (ctx, input) => band.recordPayout(ctx, input),
  }),
  defineOperation({
    id: "gigs.reverse_payout",
    tool: "reverse_payout",
    description: "Correct a payout recorded by mistake by adding a reversing entry.",
    scope: "workspace",
    kind: "write",
    confirm: true,
    http: { method: "POST", path: "/payouts/:payout_id/reverse", status: 201 },
    input: PayoutRef,
    handler: (ctx, input) => band.reversePayout(ctx, input.payout_id, input.note),
  }),

  // --- Settings (per collective) ---
  defineOperation({
    id: "gigs.get_settings",
    tool: "get_gigs_settings",
    description:
      "The collective's Gigs settings: whether members see who plays, and who can set lineups and record payouts.",
    scope: "workspace",
    kind: "read",
    http: { method: "GET", path: "/settings/gigs" },
    input: z.object({}),
    handler: (ctx) => settings.getSettings(ctx),
  }),
  defineOperation({
    id: "gigs.update_settings",
    tool: "update_gigs_settings",
    description:
      'Change the collective\'s Gigs settings (owners): lineup_visible_to_members, lineup_editors and payout_recorders ("owners" or "everyone").',
    scope: "workspace",
    kind: "write",
    role: "owner",
    http: { method: "PATCH", path: "/settings/gigs" },
    input: UpdateGigsSettingsInput,
    handler: (ctx, input) => settings.updateSettings(ctx, input),
  }),

  // --- Me (across all my workspaces; user-scoped, read-only) ---
  defineOperation({
    id: "gigs.get_my_home",
    tool: "get_my_home",
    description:
      "The signed-in person's own picture across all their workspaces: upcoming gigs they play, what they earned and received this month, what collectives and clients still owe them, and (for collectives they own) what they still owe other musicians. Never shows other people's shares.",
    scope: "user",
    kind: "read",
    http: { method: "GET", path: "/me/home" },
    input: z.object({}),
    handler: (ctx) => me.getMyHome(ctx),
  }),
];
