// Gigs module operations (docs/api.md). Each is an HTTP route under
// /api/w/:workspaceId and, from T10, an MCP tool with the same name.
import {
  CancelGigInput,
  ClientRef,
  CreateClientInput,
  CreateGigInput,
  CreateVenueInput,
  FindClientsInput,
  FindGigsInput,
  FindVenuesInput,
  GigRef,
  UpdateClientInput,
  UpdateGigInput,
  UpdateVenueInput,
  VenueRef,
} from "@assistant/shared";
import { defineOperation } from "../../core/operations.ts";
import * as c from "./services/clients.ts";
import * as v from "./services/venues.ts";
import * as g from "./services/gigs.ts";

export const gigsOperations = [
  // --- Clients ---
  defineOperation({
    id: "gigs.create_client",
    tool: "create_client",
    description: "Add a client (the person or company booking gigs).",
    scope: "workspace",
    kind: "write",
    http: { method: "POST", path: "/clients", status: 201 },
    input: CreateClientInput,
    handler: (ctx, input) => c.createClient(ctx, input),
  }),
  defineOperation({
    id: "gigs.find_clients",
    tool: "find_clients",
    description: "List clients, optionally searching by name, phone or organisation.",
    scope: "workspace",
    kind: "read",
    http: { method: "GET", path: "/clients" },
    input: FindClientsInput,
    handler: (ctx, input) => c.findClients(ctx, input),
  }),
  defineOperation({
    id: "gigs.get_client_history",
    tool: "get_client_history",
    description: "A client's details and all their gigs, newest first.",
    scope: "workspace",
    kind: "read",
    http: { method: "GET", path: "/clients/:client_id" },
    input: ClientRef,
    handler: (ctx, input) => c.clientHistory(ctx, input.client_id),
  }),
  defineOperation({
    id: "gigs.update_client",
    tool: "update_client",
    description: "Change a client's details. Omitted fields stay the same; null clears a field.",
    scope: "workspace",
    kind: "write",
    http: { method: "PATCH", path: "/clients/:client_id" },
    input: UpdateClientInput,
    handler: (ctx, input) => c.updateClient(ctx, input),
  }),
  defineOperation({
    id: "gigs.delete_client",
    tool: "delete_client",
    description: "Delete a client. Their gigs keep a reference to them.",
    scope: "workspace",
    kind: "write",
    confirm: true,
    http: { method: "DELETE", path: "/clients/:client_id" },
    input: ClientRef,
    handler: (ctx, input) => c.deleteClient(ctx, input.client_id),
  }),

  // --- Venues ---
  defineOperation({
    id: "gigs.create_venue",
    tool: "create_venue",
    description: "Add a venue.",
    scope: "workspace",
    kind: "write",
    http: { method: "POST", path: "/venues", status: 201 },
    input: CreateVenueInput,
    handler: (ctx, input) => v.createVenue(ctx, input),
  }),
  defineOperation({
    id: "gigs.find_venues",
    tool: "find_venues",
    description: "List venues, optionally searching by name or city.",
    scope: "workspace",
    kind: "read",
    http: { method: "GET", path: "/venues" },
    input: FindVenuesInput,
    handler: (ctx, input) => v.findVenues(ctx, input),
  }),
  defineOperation({
    id: "gigs.update_venue",
    tool: "update_venue",
    description: "Change a venue's details. Omitted fields stay the same; null clears a field.",
    scope: "workspace",
    kind: "write",
    http: { method: "PATCH", path: "/venues/:venue_id" },
    input: UpdateVenueInput,
    handler: (ctx, input) => v.updateVenue(ctx, input),
  }),
  defineOperation({
    id: "gigs.delete_venue",
    tool: "delete_venue",
    description: "Delete a venue. Gigs there keep a reference to it.",
    scope: "workspace",
    kind: "write",
    confirm: true,
    http: { method: "DELETE", path: "/venues/:venue_id" },
    input: VenueRef,
    handler: (ctx, input) => v.deleteVenue(ctx, input.venue_id),
  }),

  // --- Gigs ---
  defineOperation({
    id: "gigs.create_gig",
    tool: "create_gig",
    description:
      "Add a gig. Times are India time unless an offset is given. Client and venue can be given by id or exact name; ambiguous names return candidates.",
    scope: "workspace",
    kind: "write",
    http: { method: "POST", path: "/gigs", status: 201 },
    input: CreateGigInput,
    handler: (ctx, input) => g.createGig(ctx, input),
  }),
  defineOperation({
    id: "gigs.find_gigs",
    tool: "find_gigs",
    description: "List gigs by start time, filtered by date range, status, client, venue or title.",
    scope: "workspace",
    kind: "read",
    http: { method: "GET", path: "/gigs" },
    input: FindGigsInput,
    handler: (ctx, input) => g.findGigs(ctx, input),
  }),
  defineOperation({
    id: "gigs.get_gig",
    tool: "get_gig",
    description: "One gig with its client, venue and fee.",
    scope: "workspace",
    kind: "read",
    http: { method: "GET", path: "/gigs/:gig_id" },
    input: GigRef,
    handler: (ctx, input) => g.getGig(ctx, input.gig_id),
  }),
  defineOperation({
    id: "gigs.update_gig",
    tool: "update_gig",
    description:
      "Change a gig's details (not its status). Omitted fields stay the same; null clears a field.",
    scope: "workspace",
    kind: "write",
    http: { method: "PATCH", path: "/gigs/:gig_id" },
    input: UpdateGigInput,
    handler: (ctx, input) => g.updateGig(ctx, input),
  }),
  defineOperation({
    id: "gigs.confirm_gig",
    tool: "confirm_gig",
    description: "Mark an enquiry as confirmed.",
    scope: "workspace",
    kind: "write",
    http: { method: "POST", path: "/gigs/:gig_id/confirm" },
    input: GigRef,
    handler: (ctx, input) => g.setGigStatus(ctx, input.gig_id, "confirmed"),
  }),
  defineOperation({
    id: "gigs.complete_gig",
    tool: "complete_gig",
    description: "Mark a gig as played.",
    scope: "workspace",
    kind: "write",
    http: { method: "POST", path: "/gigs/:gig_id/complete" },
    input: GigRef,
    handler: (ctx, input) => g.setGigStatus(ctx, input.gig_id, "completed"),
  }),
  defineOperation({
    id: "gigs.cancel_gig",
    tool: "cancel_gig",
    description: "Cancel a gig that hasn't been played, with an optional reason.",
    scope: "workspace",
    kind: "write",
    confirm: true,
    http: { method: "POST", path: "/gigs/:gig_id/cancel" },
    input: CancelGigInput,
    handler: (ctx, input) => g.cancelGig(ctx, input),
  }),
  defineOperation({
    id: "gigs.delete_gig",
    tool: "delete_gig",
    description: "Delete a gig entered by mistake (only if no payments are recorded; otherwise cancel it).",
    scope: "workspace",
    kind: "write",
    confirm: true,
    http: { method: "DELETE", path: "/gigs/:gig_id" },
    input: GigRef,
    handler: (ctx, input) => g.deleteGig(ctx, input.gig_id),
  }),
];
