// Gig operations (docs/design/gig-centric.md). Routes live under /api; access is decided
// by each gig's own people and roles. Writes keep their idempotency and audit inside the
// gig's object.
import {
  AddEventInput,
  BriefInput,
  PickInput,
  ContactRef,
  FindContactsInput,
  SaveContactInput,
  UpdateContactInput,
  AddPersonInput,
  BookingRef,
  BookingStatusInput,
  CreateBookingInput,
  EventRef,
  FindMyGigsInput,
  GigExpenseRef,
  GigPaymentRef,
  GigPayoutRef,
  MyReportInput,
  AutofillInput,
  DuplicateCheckInput,
  FindMyTagsInput,
  PersonRef,
  RecordGigExpenseInput,
  RecordGigPaymentInput,
  RecordGigPayoutInput,
  SetEventLineupInput,
  UpdateBookingInput,
  UpdateEventInput,
  UpdatePersonInput,
  SetGigTypesInput,
  SetAttendanceInput,
} from "@assistant/shared";
import { defineOperation } from "../../core/operations.ts";
import { z } from "zod";
import * as b from "./services/bookings.ts";
import * as h from "./services/home.ts";
import * as t from "./services/tags.ts";
import * as c from "./services/contacts.ts";
import { getBrief, pick } from "./services/brief.ts";

export const bookingOperations = [
  defineOperation({
    id: "gigs.get_gig_types",
    tool: "get_gig_types",
    description: "My gig types (Public and Private unless I changed them), to use as a gig's event_type.",
    kind: "read",
    http: { method: "GET", path: "/me/gig-types" },
    input: z.object({}),
    handler: (ctx) => c.gigTypes(ctx),
  }),
  defineOperation({
    id: "gigs.set_gig_types",
    tool: "set_gig_types",
    description:
      "Replace my list of gig types (in order). Gigs keep the type they have; renaming a type doesn't change old gigs.",
    kind: "write",
    http: { method: "PUT", path: "/me/gig-types" },
    input: SetGigTypesInput,
    handler: (ctx, input) => c.setGigTypes(ctx, input.types),
  }),
  defineOperation({
    id: "gigs.create_booking",
    tool: "create_gig",
    description:
      "Create a gig with one or more events (date, time, venue) and the people on it. You become its manager. Times without an offset are India time. Optional: collective (band name) and custom tags. Check check_gig_duplicates first; for a collective, suggest_gig_people offers the people from its last gig.",
    kind: "write",
    http: { method: "POST", path: "/gigs", status: 201 },
    input: CreateBookingInput,
    handler: (ctx, input) => b.createBooking(ctx, input),
  }),
  defineOperation({
    id: "gigs.find_my_gigs",
    tool: "find_my_gigs",
    description:
      "My gigs' events, soonest first (or latest first with order=desc), optionally between two times, by status, or matching a search (title, event, client, venue). May lag a few seconds behind changes.",
    kind: "read",
    http: { method: "GET", path: "/me/gigs" },
    input: FindMyGigsInput,
    handler: (ctx, input) => b.findMyGigs(ctx, input),
  }),
  defineOperation({
    id: "gigs.get_booking",
    tool: "get_gig",
    description: "A gig's details, events and people (only for people on the gig).",
    kind: "read",
    http: { method: "GET", path: "/gigs/:gig_id" },
    input: BookingRef,
    handler: (ctx, input) => b.getBooking(ctx, input.gig_id),
  }),
  defineOperation({
    id: "gigs.update_booking",
    tool: "update_gig",
    description:
      "Change a gig's title, type, client, notes, fee or who-sees-what settings (managers). Send the version you last saw; if someone changed the gig since, you get a conflict and should reload.",
    kind: "write",
    http: { method: "PATCH", path: "/gigs/:gig_id" },
    input: UpdateBookingInput,
    handler: (ctx, input) => b.updateBooking(ctx, input),
  }),
  defineOperation({
    id: "gigs.set_booking_status",
    tool: "set_gig_status",
    description:
      "Confirm, complete, cancel or reopen a gig (managers). enquiry → confirmed → completed; enquiry or confirmed → cancelled; reopen puts a cancelled gig back as it was (a refund recorded when cancelling stays). When cancelling, give refund (rupees) to return part or all of an advance; the rest is kept as income.",
    kind: "write",
    confirm: true,
    http: { method: "POST", path: "/gigs/:gig_id/status" },
    input: BookingStatusInput,
    handler: (ctx, input) => b.setBookingStatus(ctx, input),
  }),
  defineOperation({
    id: "gigs.delete_booking",
    tool: "delete_gig",
    description: "Delete a gig entered by mistake (managers). To call off a real gig, cancel it instead.",
    kind: "write",
    confirm: true,
    http: { method: "DELETE", path: "/gigs/:gig_id" },
    input: BookingRef,
    handler: (ctx, input) => b.deleteBooking(ctx, input.gig_id),
  }),
  defineOperation({
    id: "gigs.get_booking_history",
    tool: "get_gig_history",
    description: "Who changed what on a gig, newest first (managers).",
    kind: "read",
    http: { method: "GET", path: "/gigs/:gig_id/history" },
    input: BookingRef,
    handler: (ctx, input) => b.bookingHistory(ctx, input.gig_id),
  }),
  defineOperation({
    id: "gigs.add_booking_event",
    tool: "add_gig_event",
    description:
      'Add an event to a gig, e.g. a "Reception" after the "Sangeet", or a rehearsal for it (kind rehearsal) (managers).',
    kind: "write",
    http: { method: "POST", path: "/gigs/:gig_id/events", status: 201 },
    input: AddEventInput,
    handler: (ctx, input) => b.addBookingEvent(ctx, input),
  }),
  defineOperation({
    id: "gigs.update_booking_event",
    tool: "update_gig_event",
    description: "Change an event's title, time, venue or notes (managers; send the gig's version).",
    kind: "write",
    http: { method: "PATCH", path: "/gigs/:gig_id/events/:event_id" },
    input: UpdateEventInput,
    handler: (ctx, input) => b.updateBookingEvent(ctx, input),
  }),
  defineOperation({
    id: "gigs.remove_booking_event",
    tool: "remove_gig_event",
    description: "Remove an event from a gig (managers). A gig keeps at least one event.",
    kind: "write",
    confirm: true,
    http: { method: "DELETE", path: "/gigs/:gig_id/events/:event_id" },
    input: EventRef,
    handler: (ctx, input) => b.removeBookingEvent(ctx, input.gig_id, input.event_id),
  }),
  defineOperation({
    id: "gigs.set_attendance",
    tool: "set_rehearsal_attendance",
    description:
      "Say whether you're coming to a rehearsal (going true/false). Managers can answer for someone on the gig with person_id.",
    kind: "write",
    http: { method: "PUT", path: "/gigs/:gig_id/events/:event_id/attendance" },
    input: SetAttendanceInput,
    handler: (ctx, input) => b.setAttendance(ctx, input),
  }),
  defineOperation({
    id: "gigs.add_booking_person",
    tool: "add_gig_person",
    description:
      "Add someone to a gig as a manager or player (managers). Give their user_id, their email (matched to an account if they have one) or just a name.",
    kind: "write",
    http: { method: "POST", path: "/gigs/:gig_id/people", status: 201 },
    input: AddPersonInput,
    handler: (ctx, input) => b.addBookingPerson(ctx, input),
  }),
  defineOperation({
    id: "gigs.update_booking_person",
    tool: "update_gig_person",
    description: "Change someone's role or name on a gig (managers). A gig keeps at least one manager.",
    kind: "write",
    http: { method: "PATCH", path: "/gigs/:gig_id/people/:person_id" },
    input: UpdatePersonInput,
    handler: (ctx, input) => b.updateBookingPerson(ctx, input),
  }),
  defineOperation({
    id: "gigs.remove_booking_person",
    tool: "remove_gig_person",
    description: "Remove someone from a gig (managers). A gig keeps at least one manager.",
    kind: "write",
    confirm: true,
    http: { method: "DELETE", path: "/gigs/:gig_id/people/:person_id" },
    input: PersonRef,
    handler: (ctx, input) => b.removeBookingPerson(ctx, input.gig_id, input.person_id),
  }),
  // --- Money (step 3). Every money write asks for confirmation from assistants. ---------
  defineOperation({
    id: "gigs.record_gig_payment",
    tool: "record_gig_payment",
    description: "Record money received from the client for a gig (managers). Amount in rupees or paise.",
    kind: "write",
    confirm: true,
    http: { method: "POST", path: "/gigs/:gig_id/payments", status: 201 },
    input: RecordGigPaymentInput,
    handler: (ctx, input) => b.recordGigPayment(ctx, input),
  }),
  defineOperation({
    id: "gigs.reverse_gig_payment",
    tool: "reverse_gig_payment",
    description:
      "Correct a client payment recorded by mistake (managers). Adds a reversing entry; nothing is deleted.",
    kind: "write",
    confirm: true,
    http: { method: "POST", path: "/gigs/:gig_id/payments/:payment_id/reverse", status: 201 },
    input: GigPaymentRef,
    handler: (ctx, input) => b.reverseGigPayment(ctx, input),
  }),
  defineOperation({
    id: "gigs.record_gig_expense",
    tool: "record_gig_expense",
    description: "Record an expense for a gig, optionally for one event (managers).",
    kind: "write",
    confirm: true,
    http: { method: "POST", path: "/gigs/:gig_id/expenses", status: 201 },
    input: RecordGigExpenseInput,
    handler: (ctx, input) => b.recordGigExpense(ctx, input),
  }),
  defineOperation({
    id: "gigs.remove_gig_expense",
    tool: "remove_gig_expense",
    description: "Remove an expense entered by mistake (managers).",
    kind: "write",
    confirm: true,
    http: { method: "DELETE", path: "/gigs/:gig_id/expenses/:expense_id" },
    input: GigExpenseRef,
    handler: (ctx, input) => b.removeGigExpense(ctx, input.gig_id, input.expense_id),
  }),
  defineOperation({
    id: "gigs.set_event_lineup",
    tool: "set_event_lineup",
    description:
      "Set who plays an event, their part and share (managers; replaces the event's lineup; send the gig's version). People must be on the gig first. Shares: per person, split equally, or by percent of split_total.",
    kind: "write",
    confirm: true,
    http: { method: "PUT", path: "/gigs/:gig_id/events/:event_id/lineup" },
    input: SetEventLineupInput,
    handler: (ctx, input) => b.setEventLineup(ctx, input),
  }),
  defineOperation({
    id: "gigs.record_gig_payout",
    tool: "record_gig_payout",
    description: "Record money paid to someone on a gig for their share (managers).",
    kind: "write",
    confirm: true,
    http: { method: "POST", path: "/gigs/:gig_id/payouts", status: 201 },
    input: RecordGigPayoutInput,
    handler: (ctx, input) => b.recordGigPayout(ctx, input),
  }),
  defineOperation({
    id: "gigs.reverse_gig_payout",
    tool: "reverse_gig_payout",
    description:
      "Correct a payout recorded by mistake (managers). Adds a reversing entry; nothing is deleted.",
    kind: "write",
    confirm: true,
    http: { method: "POST", path: "/gigs/:gig_id/payouts/:payout_id/reverse", status: 201 },
    input: GigPayoutRef,
    handler: (ctx, input) => b.reverseGigPayout(ctx, input),
  }),
  // --- Home and reports (step 4): from my own summaries only. ------------------------
  defineOperation({
    id: "gigs.get_home",
    tool: "get_home",
    description:
      "My Home: next events, this month's gigs and earnings, what's owed to me, and for gigs I manage, what's still due from clients and still to pay the people playing. May lag a few seconds behind changes.",
    kind: "read",
    http: { method: "GET", path: "/me/overview" },
    input: z.object({}),
    handler: (ctx) => h.getHome(ctx),
  }),
  defineOperation({
    id: "gigs.get_my_report",
    tool: "get_my_report",
    description:
      "My money between two dates (India), by month and by gig: my shares, paid and owed; for gigs I manage also fee, received, expenses and net. Cancelled gigs are left out unless you ask for them by status. Filter by role or client.",
    kind: "read",
    http: { method: "GET", path: "/me/report" },
    input: MyReportInput,
    handler: (ctx, input) => h.getMyReport(ctx, input),
  }),
  // --- Tags, autofill, duplicates (step 5) -------------------------------------------
  defineOperation({
    id: "gigs.find_my_tags",
    tool: "find_my_tags",
    description:
      "Collectives and custom tags on gigs I'm on, most used first (for suggestions and report filters).",
    kind: "read",
    http: { method: "GET", path: "/me/tags" },
    input: FindMyTagsInput,
    handler: (ctx, input) => t.findMyTags(ctx, input),
  }),
  defineOperation({
    id: "gigs.suggest_gig_people",
    tool: "suggest_gig_people",
    description:
      "People from my latest gig with this collective (whose lineup I could see), to fill in a new gig. Names only: no roles or amounts.",
    kind: "read",
    http: { method: "GET", path: "/me/autofill" },
    input: AutofillInput,
    handler: (ctx, input) => t.autofill(ctx, input),
  }),
  defineOperation({
    id: "gigs.check_gig_duplicates",
    tool: "check_gig_duplicates",
    description:
      "Before creating a gig: does someone I've played with already have a gig that day at this venue or for this client? Shows their name so I can ask to be added instead. Never blocks.",
    kind: "read",
    http: { method: "GET", path: "/me/duplicates" },
    input: DuplicateCheckInput,
    handler: (ctx, input) => t.checkDuplicates(ctx, input),
  }),
  defineOperation({
    id: "gigs.get_brief",
    tool: "get_brief",
    description:
      "A short spoken answer (for Siri): my next gig, my gigs this week, who owes me, what clients owe on gigs I manage, or what I still have to pay out. Returns text to read out and the items behind it.",
    kind: "read",
    http: { method: "GET", path: "/me/brief" },
    input: BriefInput,
    handler: (ctx, input) => getBrief(ctx, input),
  }),
  defineOperation({
    id: "gigs.pick",
    tool: "pick_gig_or_person",
    description:
      "Choices for a Siri Shortcut's list: my gigs matching q (label → gig id), or with gig_id the other people on that gig (name → person id).",
    kind: "read",
    http: { method: "GET", path: "/me/pick" },
    input: PickInput,
    handler: (ctx, input) => pick(ctx, input),
  }),
  // Address book
  defineOperation({
    id: "gigs.find_contacts",
    tool: "find_contacts",
    description:
      "My address book: clients, venues and people, most recently used first. Filled in from gigs I manage and by me. Use it to fill in a new gig's client, venue and people.",
    kind: "read",
    http: { method: "GET", path: "/me/contacts" },
    input: FindContactsInput,
    handler: (ctx, input) => c.findContacts(ctx, input),
  }),
  defineOperation({
    id: "gigs.save_contact",
    tool: "save_contact",
    description:
      "Add a client, venue or person to my address book. Gigs keep their own copy of the details, so the address book never changes past gigs.",
    kind: "write",
    http: { method: "POST", path: "/me/contacts", status: 201 },
    input: SaveContactInput,
    handler: (ctx, input) => c.saveContact(ctx, input),
  }),
  defineOperation({
    id: "gigs.update_contact",
    tool: "update_contact",
    description: "Change a contact's name, phone, email, city or notes (null clears a field).",
    kind: "write",
    http: { method: "PATCH", path: "/me/contacts/:contact_id" },
    input: UpdateContactInput,
    handler: (ctx, input) => c.updateContact(ctx, input),
  }),
  defineOperation({
    id: "gigs.remove_contact",
    tool: "remove_contact",
    description: "Remove a contact from my address book. Gigs that used it are not changed.",
    kind: "write",
    confirm: true,
    http: { method: "DELETE", path: "/me/contacts/:contact_id" },
    input: ContactRef,
    handler: (ctx, input) => c.removeContact(ctx, input.contact_id),
  }),
];
