// Generates the D1 migration SQL for Better Auth's tables from src/auth.ts.
// Usage: pnpm gen:migration  (writes migrations/0001_better_auth.sql)
import { DatabaseSync } from "node:sqlite";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { getMigrations } from "better-auth/db/migration";
import { authOptions } from "../src/auth.ts";

const options = authOptions({
  baseURL: "http://localhost:8787",
  secret: "migration-generation-only-not-a-real-secret",
  database: new DatabaseSync(":memory:"),
  google: { clientId: "x", clientSecret: "x" },
});

const { compileMigrations } = await getMigrations(options);
const sql = await compileMigrations();
const out = join(import.meta.dirname, "../migrations/0001_better_auth.sql");
writeFileSync(out, `-- Generated by scripts/gen-migration.ts. Do not edit; regenerate.\n${sql}\n`);
console.log(`wrote ${out}`);
